{{- if and .Values.webhook.enabled .Values.webhook.url (not .Values.webhook.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-cert-renewer.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-cert-renewer.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encode the webhook URL
  webhook-url: {{ .Values.webhook.url | b64enc | quote }}
{{- end }}
